# Task
Apply Polynomial Regression by taking two predictors

In [6]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [7]:
brains=pd.read_csv("https://raw.githubusercontent.com/AP-Skill-Development-Corporation/DataScienceUsingPython-Internship-SRM-University/main/Datasets/Datasets-master/Regression/headbrain.csv")
brains

     Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0         1          1             4512                 1530
1         1          1             3738                 1297
2         1          1             4261                 1335
3         1          1             3777                 1282
4         1          1             4177                 1590
5         1          1             3585                 1300
6         1          1             3785                 1400
7         1          1             3559                 1255
8         1          1             3613                 1355
9         1          1             3982                 1375
10        1          1             3443                 1340
11        1          1             3993                 1380
12        1          1             3640                 1355
13        1          1             4208                 1522
14        1          1             3832                 1208
15        1          1             3876                 1405
16        1          1             3497                 1358
17        1          1             3466                 1292
18        1          1             3095                 1340
19        1          1             4424                 1400
20        1          1             3878                 1357
21        1          1             4046                 1287
22        1          1             3804                 1275
23        1          1             3710                 1270
24        1          1             4747                 1635
25        1          1             4423                 1505
26        1          1             4036                 1490
27        1          1             4022                 1485
28        1          1             3454                 1310
29        1          1             4175                 1420
..      ...        ...              ...                  ...
207       2          2             3995                 1296
208       2          2             3318                 1175
209       2          2             2720                  955
210       2          2             2937                 1070
211       2          2             3580                 1320
212       2          2             2939                 1060
213       2          2             2989                 1130
214       2          2             3586                 1250
215       2          2             3156                 1225
216       2          2             3246                 1180
217       2          2             3170                 1178
218       2          2             3268                 1142
219       2          2             3389                 1130
220       2          2             3381                 1185
221       2          2             2864                 1012
222       2          2             3740                 1280
223       2          2             3479                 1103
224       2          2             3647                 1408
225       2          2             3716                 1300
226       2          2             3284                 1246
227       2          2             4204                 1380
228       2          2             3735                 1350
229       2          2             3218                 1060
230       2          2             3685                 1350
231       2          2             3704                 1220
232       2          2             3214                 1110
233       2          2             3394                 1215
234       2          2             3233                 1104
235       2          2             3352                 1170
236       2          2             3391                 1120

[237 rows x 4 columns]

In [8]:
brains.shape

(237, 4)

In [9]:
# Checking for null values

brains.isnull().sum()

Gender                 0
Age Range              0
Head Size(cm^3)        0
Brain Weight(grams)    0
dtype: int64

In [10]:
x=brains.drop(["Brain Weight(grams)","Age Range"],axis=1)
y=brains["Brain Weight(grams)"]

In [11]:
# Creating polynomial degree

from sklearn.preprocessing import PolynomialFeatures

poly=PolynomialFeatures(degree=5)
x_poly=poly.fit_transform(x)

In [12]:
re=LinearRegression()

re.fit(x_poly,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
y_pred=re.predict(x_poly)

In [14]:
from sklearn.metrics import r2_score
r2_score(y,y_pred)*100

65.11611334447845